import { brand_name } from "data";

const Head = () => (
    <>
        <title>{brand_name}</title>

        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
    </>
);

export default Head;
